### ISSUE TITLE
[Documentation] Implementation Details?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-cw-video#12]
Hey there Andy,

If you have some time and feel motivated, how was this made? Could this be
added to some docu-file or the wiki, if you have time?

I remember you mentioned this a while ago; I am surprised that this already
works ... I am kind of missing the in-between stuff so I am a bit confused.
Have to find out how that works and what limitations/opportunities are
possible now (other than, of course, viewing videos).

**Comment by AndyObtiva** [comment]
First of all, I would like to clarify that this Video custom widget is for [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) only, which runs in JRuby and is 100% mature ([SWT](https://www.eclipse.org/swt/) is 100% complete and rich in community support). There is still no such control in [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui) running in standard Ruby yet. I just updated the [README](https://github.com/AndyObtiva/glimmer-cw-video/blob/master/README.md) to clarify that the Video custom widget is for [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) specifically.

Secondly, I am surprised you ask such a question regarding an open-source project. The source code is open to the public and you are an expert software engineer, so you should have no problem reading the code and getting your question answered directly that way.

There is no need for over-documentation regarding open-source project implementations because the source is open to the public for everyone to see. It would answer your questions more than anything I'd write as documentation. It's better to reserve documentation for describing the API and how to use a library, not how it works. The code tells you how it works.

I am closing this issue as a result as I believe the open-source nature of the project fully addresses it.
